### ISSUE TITLE
After installing When I clicked on  General ->content Management  I got following errror

### ISSUE THREAD

**Issue by tousif12** [experius/Mage2-Module-WysiwygDownloads#11]
After installation When I clicked on  General ->content Management  I got following error

> Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: Experius\WysiwygDownloads\Block\Adminhtml\System\Config\Form\Field\Filetypes
> Exception #1 (ReflectionException): Class Experius\WysiwygDownloads\Block\Adminhtml\System\Config\Form\Field\Filetypes does not exist

where is problem actually ? I put code in  

> app/code/experius/module-wysiwygdownloads

**Comment by lewisvoncken** [comment]
upload the folder to:

app/code/Experius/WysiwygDownloads

and then enable the module manually (this step is optional)

**Comment by tousif12** [comment]
Resolved thank you.
