### ISSUE TITLE
How to Install on Magento 2.1.0

### ISSUE THREAD

**Issue by tabatsoy** [experius/Mage2-Module-WysiwygDownloads#13]
Hi there,

How to install this on Magento 2.1.0, i'm new in magento so if you could kindly give me step by step installation would be of good help.

Many thanks

**Comment by lewisvoncken** [comment]
@tabatsoy 

You can install through composer using the composer name:

> experius/module-wysiwygdownloads

run the following command:

> composer require experius/module-wysiwygdownloads

**Comment by tabatsoy** [comment]
do i need to upload it on my server before running the composer?

**Comment by lewisvoncken** [comment]
@tabatsoy 
for more information how to install a Magento 2 Module see the magento dev docs

http://devdocs.magento.com/guides/v2.0/cloud/howtos/install-components.html

**Comment by tabatsoy** [comment]
i'm working on a live magento site and honestly i only know how to upload via ftp. any tips? thanks
