### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by sarfaraj-php** [experius/Mage2-Module-WysiwygDownloads#14]
I have installed this module and do as you said but it is not dispaly actual pdf file link to frontend cms-page/product detail page.

Also insert image button not working after install this module.

**Comment by lauzis** [comment]
@sarfaraj-php you should provide as much details about your setup as you can.
- What is magento version?
- Environment (php version, os, ....)
- Does the insert image button works, if the module is disabled?
- Did you run cache clean, regenerate commands?
