### ISSUE TITLE
How can I remove this module?

### ISSUE THREAD

**Issue by sdp49** [experius/Mage2-Module-WysiwygDownloads#18]
LogicException: Circular dependency: Magento\Framework\Logger\Monolog depends on Magento\Store\Model\Config\Processor\Fallback and vice versa.

I receive above error after installing from composer and have not been able to access my site.
Can you help me?

**Comment by cjnewbs** [comment]
@sdp49 Are you still having this issue? I have just installed on a EE 2.3.1 instance and seems to be ok.

running `bin/magento module:disable Experius_WysiwygDownloads` then cleaning the cache should do the trick. There are no setup scripts so there should be no traces in the DB.
