### ISSUE TITLE
Not working url

### ISSUE THREAD

**Issue by aliciajanssen** [experius/Mage2-Module-WysiwygDownloads#2]
Thank you for the great module, but i have one problem with it.

Everything goes well but i have a problem with adding the link. When i add a link (first adding the file through the url button, then add file, then add url) i'll get the wrong url. 

It seems like he sees the file as an image file. In your explanation you use a "NGINX redirect". Can you clarify what that is? 
Maybe that's the problem.

**Comment by lewisvoncken** [comment]
Hello @aliciajanssen 

Great to hear that you are using the module!

The given example for a NGINX redirect is only necessary if you use store code in URL and you want to dynamically use the uploaded file in other modules which are based on path.

Could you please sent the plain HTML which has been inserted in the WYSIWYG editor?

**Comment by aliciajanssen** [comment]
/admin/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvUHJvZHVjdGVuL3BkZi1zYW1wbGVfMS5wZGYifX0,/key/3f418cdc25787958ac98abab890bf7f771d066f4d85144fc686c1af61e848c10/

When i click on the link i'll get an report message. This is:
Warning: getimagesize(pub/static/adminhtml/Magento/backend/nl_NL/Magento_Cms/images/wysiwyg_skin_image.png): failed to open stream: No such file or directory in [url]/vendor/magento/framework/Image/Adapter/AbstractAdapter.php on line 304

**Comment by lewisvoncken** [comment]
Did you add the link through the anchor option or through the image option and what happens if you save the element and then test the link in the frontend?

**Comment by aliciajanssen** [comment]
I added the link through the anchor option.
If i save the element and i test it in the frontend i get that error report.

**Comment by lewisvoncken** [comment]
I can't reproduce the issue. Could you please clarify where you use the WYSIWYG editor and which Magento 2 version you are running. 

Besides that this module could also be interesting https://github.com/experius/Magento-2-Module-Experius-File-Manager

**Comment by lewisvoncken** [comment]
@aliciajanssen 

do you use the popup wywisyg editor or the inline one because if you use it with images (default Magento) it is possible that you save the admin url.

**Comment by lewisvoncken** [comment]
@aliciajanssen  let me know if this issue can be closed?

**Comment by VladSuciu76** [comment]
hi @aliciajanssen!
Have you managed to find the solution for this issue?
Thank you

**Comment by lewisvoncken** [comment]
hi @VladSuciu76 and @aliciajanssen 

This is an issue in Magento and is solved in 2.2.2 for more information see the following commit:

https://github.com/magento/magento2/commit/62378774f239c2019e39bdd353c8c6c674b54fb1
