### ISSUE TITLE
PHP deprication error after upgrade to PHP 8.1

### ISSUE THREAD

**Issue by hannes011** [experius/Mage2-Module-WysiwygDownloads#24]
Hi everyone,

After upgrading to PHP 8 there is an error occurring for the image pagebuilder element if you choose "select from gallery".

The error appears by not displaying any of the gallery content (only the directory tree). Furthermore, you'll find the following log in your system.log:
`Exception: Deprecated Functionality: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in vendor/experius/module-wysiwygdownloads/Helper/Settings.php on line 86 in /var/www/html/magento/vendor/magento/framework/App/ErrorHandler.php:62`

Prerequisite is that you've NOT added any additional file types to: Config > General > Content Management > WYSIWYG Options > Extra Allowed Filetypes in the WYSIWYG-editor

**Quick workaround** would be also to just add any type to that configuration.

I'm on Magento 2.4.5

**Comment by hannes011** [comment]
Solution to fix this issue I've created the following patch:

```
diff --git a/Helper/Settings.php b/Helper/Settings.php
index 03c9641..8868b64 100644
--- a/Helper/Settings.php
+++ b/Helper/Settings.php
@@ -83,7 +83,7 @@ class Settings extends \Magento\Framework\App\Helper\AbstractHelper
 	public function getExtraFiletypes()
 	{
       $filetypes = array();
-      $settings = json_decode($this->getConfigValue(self::CONFIG_PATH_FILETYPES));
+      $settings = json_decode($this->getConfigValue(self::CONFIG_PATH_FILETYPES) ?? '[]');
       if ($settings) {
           foreach($settings as $setting){
               $filetypes[] =  $setting->extension;

```

**Comment by jornwildenbeest** [comment]
@hannes011 ran in to the same thing. 

Quick fix is also to just add an empty array in the settings:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/25662412/223673033-ff501de1-70bc-494a-875f-ffae7b2791a3.png">

EDIT: sorry, jus saw that you added the samething in the description of the issue
