### ISSUE TITLE
Media manager doesn't show pdfs in 2.4.6

### ISSUE THREAD

**Issue by HenrivantSant** [experius/Mage2-Module-WysiwygDownloads#27]
The new media management of Magento doesn't show pdfs. They're uploaded successfully, however they're not available in the media management to actually use them. 

![image](https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/assets/33251446/728fe6a5-5d41-436e-8786-d2553664fc69)

**Comment by tweetyx** [comment]
it's seems 👍 
https://magento.stackexchange.com/questions/337952/uploading-svg-and-pdf-in-the-new-media-gallery

"```
Additionally, that part comes from vendor/magento/module-media-gallery-synchronization/etc/di.xml:

<type name="Magento\MediaGallerySynchronization\Model\FetchMediaStorageFileBatches">
    <arguments>
        <argument name="batchSize" xsi:type="number">100</argument>
        <argument name="fileExtensions" xsi:type="array">
            <item name="jpg" xsi:type="string">jpg</item>
            <item name="jpeg" xsi:type="string">jpeg</item>
            <item name="gif" xsi:type="string">gif</item>
            <item name="png" xsi:type="string">png</item>
        </argument>
    </arguments>
</type>
You should add your custom extensions in that file too, so it make that files recognizable.

Place that in your di.xml:

<type name="Magento\MediaGallerySynchronization\Model\FetchMediaStorageFileBatches">
    <arguments>
        <argument name="fileExtensions" xsi:type="array">
            <item name="pdf" xsi:type="string">pdf</item>
            <item name="svg" xsi:type="string">svg</item>
        </argument>
    </arguments>
</type>
```

"

i have problem with imagemagik when i synchronize
php bin/magento media-gallery:sync

so i have desactivate this new module
https://experienceleague.adobe.com/docs/commerce-admin/content-design/media/gallery/media-gallery.html#media-gallery-demo

**Comment by xnhinzkyx** [comment]
I got same issue. Also the file has not been added to media_gallery_asset table. It's uploaded but you can't see the file.

Magento 2.4.6
PHP 8.1

**Comment by borisvankatwijk** [comment]
Hi @HenrivantSant ,
cc @tweetyx, @xnhinzkyx,

These things should be fixed in the latest release:
https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/releases/tag/1.2.1

Credits to @mhaagen85

Kind regards
