### ISSUE TITLE
Product image is not uploading

### ISSUE THREAD

**Issue by Nehace40** [experius/Mage2-Module-WysiwygDownloads#3]
I am using 2.1.3

when i try to upload image in product it gives this error

{"error":"Notice: Undefined index: extension in app\/code\/Experius\/WysiwygDownloads\/Image\/Adapter\/Gd2.php on line 35","errorcode":0}

**Comment by lewisvoncken** [comment]
problem is solved in 1.0.7

https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/commit/babbdb67d77765c9339e3d2bcf05afecfc232331
