### ISSUE TITLE
MP4 file uploading successfully but its preview not available in gallery column grid

### ISSUE THREAD

**Issue by parveenkhan22** [experius/Mage2-Module-WysiwygDownloads#34]
Hi,
I included an mp4 video, which was successfully posted. It is visible in the pub/media folder, but I need to be able to select the preview in the uploader grid, just like images.

![image](https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/assets/57412408/f870bbce-f90f-4917-bea8-0b656b84866c)

Any help would be greatly appreciated.
Thank you.

**Comment by iriks-it** [comment]
Fixed in 1.2.4, Please upgrade.
