### ISSUE TITLE
is_writable(): Argument #1 ($filename) must be of type string, null given in 

### ISSUE THREAD

**Issue by nilaykumardeveloper** [experius/Mage2-Module-WysiwygDownloads#35]
[2024-03-15T09:26:26.043427+00:00] report.CRITICAL: TypeError: is_writable(): Argument #1 ($filename) must be of type string, null given in /app/bqztqkvnl2vqi/vendor/magento/framework/Image/Adapter/AbstractAdapter.php:690
Stack trace:
#0 /app/bqztqkvnl2vqi/vendor/magento/framework/Image/Adapter/AbstractAdapter.php(690): is_writable()
#1 /app/bqztqkvnl2vqi/app/code/Experius/WysiwygDownloads/Image/Adapter/Gd2.php(66): Magento\Framework\Image\Adapter\AbstractAdapter->_prepareDestination()
#2 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(58): Experius\WysiwygDownloads\Image\Adapter\Gd2->save()
#3 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(138): Experius\WysiwygDownloads\Image\Adapter\Gd2\Interceptor->___callParent()
#4 /app/bqztqkvnl2vqi/vendor/magento/module-remote-storage/Plugin/Image.php(160): Experius\WysiwygDownloads\Image\Adapter\Gd2\Interceptor->Magento\Framework\Interception\{closure}()
#5 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(135): Magento\RemoteStorage\Plugin\Image->aroundSave()
#6 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(153): Experius\WysiwygDownloads\Image\Adapter\Gd2\Interceptor->Magento\Framework\Interception\{closure}()
#7 /app/bqztqkvnl2vqi/generated/code/Experius/WysiwygDownloads/Image/Adapter/Gd2/Interceptor.php(32): Experius\WysiwygDownloads\Image\Adapter\Gd2\Interceptor->___callPlugins()
#8 /app/bqztqkvnl2vqi/vendor/magento/framework/Image.php(75): Experius\WysiwygDownloads\Image\Adapter\Gd2\Interceptor->save()
#9 /app/bqztqkvnl2vqi/vendor/amasty/blog-sys/Model/ImageProcessor.php(162): Magento\Framework\Image->save()
#10 /app/bqztqkvnl2vqi/vendor/amasty/blog-sys/Model/ResourceModel/Posts.php(385): Amasty\Blog\Model\ImageProcessor->processCategoryIcon()
#11 /app/bqztqkvnl2vqi/vendor/amasty/blog-sys/Model/ResourceModel/Posts.php(364): Amasty\Blog\Model\ResourceModel\Posts->saveImage()
#12 /app/bqztqkvnl2vqi/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(841): Amasty\Blog\Model\ResourceModel\Posts->_afterSave()
#13 /app/bqztqkvnl2vqi/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(402): Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves()
#14 /app/bqztqkvnl2vqi/vendor/amasty/blog-sys/Model/Repository/PostRepository.php(99): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save()
#15 /app/bqztqkvnl2vqi/vendor/amasty/blog-sys/Controller/Adminhtml/Posts/Save.php(63): Amasty\Blog\Model\Repository\PostRepository->save()
#16 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(58): Amasty\Blog\Controller\Adminhtml\Posts\Save->execute()
#17 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(138): Amasty\Blog\Controller\Adminhtml\Posts\Save\Interceptor->___callParent()
#18 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(153): Amasty\Blog\Controller\Adminhtml\Posts\Save\Interceptor->Magento\Framework\Interception\{closure}()
#19 /app/bqztqkvnl2vqi/generated/code/Amasty/Blog/Controller/Adminhtml/Posts/Save/Interceptor.php(23): Amasty\Blog\Controller\Adminhtml\Posts\Save\Interceptor->___callPlugins()
#20 /app/bqztqkvnl2vqi/vendor/magento/framework/App/Action/Action.php(111): Amasty\Blog\Controller\Adminhtml\Posts\Save\Interceptor->execute()
#21 /app/bqztqkvnl2vqi/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#22 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#23 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(138): Amasty\Blog\Controller\Adminhtml\Posts\Save\Interceptor->___callParent()
#24 /app/bqztqkvnl2vqi/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Amasty\Blog\Controller\Adminhtml\Posts\Save\Interceptor->Magento\Framework\Interception\{closure}()
#25 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#26 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(153): Amasty\Blog\Controller\Adminhtml\Posts\Save\Interceptor->Magento\Framework\Interception\{closure}()
#27 /app/bqztqkvnl2vqi/generated/code/Amasty/Blog/Controller/Adminhtml/Posts/Save/Interceptor.php(32): Amasty\Blog\Controller\Adminhtml\Posts\Save\Interceptor->___callPlugins()
#28 /app/bqztqkvnl2vqi/vendor/magento/framework/App/FrontController.php(245): Amasty\Blog\Controller\Adminhtml\Posts\Save\Interceptor->dispatch()
#29 /app/bqztqkvnl2vqi/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#30 /app/bqztqkvnl2vqi/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#31 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#32 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#33 /app/bqztqkvnl2vqi/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#34 /app/bqztqkvnl2vqi/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#35 /app/bqztqkvnl2vqi/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#36 /app/bqztqkvnl2vqi/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#37 /app/bqztqkvnl2vqi/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#38 {main} [] []

**Comment by zhovnirigor** [comment]
Fixed by https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/pull/38

**Comment by iriks-it** [comment]
Fixed in 1.2.4, Please upgrade.
