### ISSUE TITLE
GD2 interaction broken after upgrading extension

### ISSUE THREAD

**Issue by indykoning** [experius/Mage2-Module-WysiwygDownloads#36]
Hi, after upgrading this module above 1.2.0 calling functions like `getOriginalHeight()` on the image always returns null.

This seems to be due to this commit

https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/commit/f8d3824ccb316034f0b593f185c2ecab93fffd03

in combination with this check https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/blob/master/Image/Adapter/Gd2.php#L49

where it will no longer open the file if it matches the whitelisted file pattern

**Comment by zhovnirigor** [comment]
Fixed by https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/pull/38

**Comment by iriks-it** [comment]
Fixed in 1.2.4, Please upgrade.
