### ISSUE TITLE
After upgrading to 1.2.3 version, no renditions are generated in wysiwyg/media library

### ISSUE THREAD

**Issue by ganeddact** [experius/Mage2-Module-WysiwygDownloads#37]
Using any media library (old or new) in Magento 2.4.6-p3 (and p4), if an image is uploaded using "Upload image / file", the renditions are not generated, so in the gallery a "image coming soon" placeholder is shown, but if you open the detail of the image, it is there, so it's loaded in the correct place.
Just missing renditions, making the media library unusable.
If I disable this module, images get their renditions immediately generated and shown in the media library list.

**Comment by zhovnirigor** [comment]
Fixed by https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/pull/38

**Comment by dennismetz** [comment]
Can we make a new release out of this?
We have the same problem with version 1.2.3

**Comment by iriks-it** [comment]
Fixed in 1.2.4, Please upgrade.
