### ISSUE TITLE
not showing thumbs in admin after image upload

### ISSUE THREAD

**Issue by awasemiller** [experius/Mage2-Module-WysiwygDownloads#6]
Thank you for the great module, but i have one problem with it.

![bildschirmfoto 2017-09-20 um 16 44 22](https://user-images.githubusercontent.com/30178722/30651034-cd9c998c-9e24-11e7-9f1f-26f777ec0633.png)
![bildschirmfoto 2017-09-20 um 16 49 11](https://user-images.githubusercontent.com/30178722/30651037-ce3745f4-9e24-11e7-9b43-4344691a7ab5.png)

**src is correct:**
`<img src="http://domain.com/pub/media/wysiwyg/.thumbs/home/home-t-shirts.png?rand=1505918839" alt="home-t-shirts.png">`

**src is incorrect:**
`<img src="http://domain.com/admin_111/cms/wysiwyg_images/thumbnail/file/aHRtbC1jaGVhdC1zaGVldC5wbmc-/key/08c5525fa3b16c91f2ad0f757282e78f6abf1f797e8c30628598f1b3824934d8/" alt="html-cheat-sheet.png">`

**Comment by tomassouto** [comment]
Same problem here.

**Comment by lewisvoncken** [comment]
hi @awasemiller  and @tomassouto   

This is an issue in Magento and is solved in 2.2.2 for more information see the following commit:

https://github.com/magento/magento2/commit/62378774f239c2019e39bdd353c8c6c674b54fb1

**Comment by lewisvoncken** [comment]
@awasemiller and @tomassouto 

I have just added this issue to the readme 

https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/blob/master/README.md#important-issue-in-magento--22

**Comment by LiamKarlMitchell** [comment]
Thumbnails not showing in Magento 2.3.2 but the patch noted in the readme appears to be applied.

Related:
https://github.com/magento/magento2/commit/62378774f239c2019e39bdd353c8c6c674b54fb1
https://github.com/magento/magento2/issues/9850

**Comment by ant0x64** [comment]
Why have you used the name started with Dot instead of normal path name? 
Basically it used as a system area so this path have sometime forbidden
For example Cloudways show 403 for thumbnails in wysiwyg 

https://i.imgur.com/dR6YT18.png
https://www.ubertheme.com/question/cloudways-says-we-cant-set-up-nginx-config/
