### ISSUE TITLE
Facing the same problem https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/issues/2

### ISSUE THREAD

**Issue by vikaskumra** [experius/Mage2-Module-WysiwygDownloads#8]
Thanks for writing a module . Its really helpful however i am experiencing the same problem as mentioned in this thread:

https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads/issues/2

Below is the html of editor:

PDF File uploads without any problem, but Its generating/pasting a link like below for PDF file. I am using insert/edit link in inline wysiwyg editor

http://discountpoolsdirect-magento.com/pooladmin/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvUERGL0JlbGl6ZV9Bc2FoaV81MmluX0JyYWNlZF9PdmFsMjAxMS5wZGYifX0,/key/403d9a69f6ea5c72e8474a5a9085ee5b4fe00020eb32583e7c808aa59284d965/"
please suggest.

Thanks
Vikas

**Comment by VladSuciu76** [comment]
Hi @vikaskumra 
I have the same issue, any luck on fixing that?
Thank you

**Comment by vikaskumra** [comment]
No Dear, Sorry! Please let me know if you manage to fix this.

Thanks
Vikas

**Comment by lewisvoncken** [comment]
hi @VladSuciu76 and @vikaskumra  

This is an issue in Magento and is solved in 2.2.2 for more information see the following commit:

https://github.com/magento/magento2/commit/62378774f239c2019e39bdd353c8c6c674b54fb1
