### ISSUE TITLE
will it work for .stl file ?

### ISSUE THREAD

**Issue by tousif12** [experius/Mage2-Module-WysiwygDownloads#9]
hi , thanks for great extension. I want to upload .stl file. where I need to change ?

**Comment by lewisvoncken** [comment]
Hi @tousif12 

_The following filetypes are available by default and it is possible to add extra filetypes to the allowed filetypes in the configuration of the module (General > Content Management > WYSIWYG Options > Extra Allowed Filetypes):_

**Word (doc, docm, docx)
Excel (csv, xml, xls, xlsx)
PDF (pdf)
Compressed Folder (zip, tar)**

This is also mentioned in the readme:

https://github.com/experius/Magento-2-Module-Experius-WysiwygDownloads#main-functionalities

**Comment by tousif12** [comment]
Sorry for asking general question as no other way to confirm it. I tried to found installation instruction but didnt get. I dont know where this extension folder to put ? can you guide
